// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvsrhhqctrdnkligdkzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12c3JoaHFjdHJkbmtsaWdka3pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1ODY0NjIsImV4cCI6MjA3MTE2MjQ2Mn0.Jo7qXz2ez5Jmzx2-wnmPIhQFtYtghnEh39tvg4hi_nI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});